name: "Deploy to personal webiste" # Name of your workflow

on:
  push:
    branches:
      - production # The trigger of the this workflow

jobs:
  build:
    runs-on: ubuntu-latest # Action uses Docker so only Linux is supported
    steps:
      - uses: actions/checkout@v1 # Checkout your triggered branch
      - uses: enriikke/gatsby-gh-pages-action@v2 # Uses this action to run further steps
        with:
          publishBranch: "master" # Not required, default publishing branch is master
          access-token: ${{ secrets.ACCESS_TOKEN }} # Your personal access token of GitHub, read more below of how to obtain one and keep it safe
          name: "Dev Thagichu" # Not required, default to action's maintainer
          email: "inf0@devthagichu.com" # Not required, default to action's maintainer
          contentfulSpace: ${{ secrets.CONTENTFUL_SPACEID }} # Your Space ID in Contentful
          contentfulToken: ${{ secrets.CONTENTFUL_ACCESSTOKEN }}
