name: "Deploy to personal webiste" # Name of your workflow

on:
  push:
    branches:
      - production # The trigger of the this workflow

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn
      - run: yarn build
        env:
          contentfulSpace: ${{ secrets.CONTENTFUL_SPACEID }}
          contentfulToken: ${{ secrets.CONTENTFUL_ACCESSTOKEN }}
      - uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: "public"
          remoteDir: "."
          options: "--delete --asci"
